# Подключения
listen_addresses = '*'
port = 5432
max_connections = 100

# Настройки производительности
shared_buffers = 128MB
dynamic_shared_memory_type = posix

# Логирование
log_destination = 'stderr'
logging_collector = off
log_statement = 'all'
log_connections = on
log_disconnections = on

# Настройки времени
timezone = 'UTC'